// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaldijwmfdkjqgrvcbbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hbGRpandtZmRranFncnZjYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDQ0NzQsImV4cCI6MjA3MjI4MDQ3NH0.gzbx3aGCMZUZ7qmtl6dmuRl_yzRysliY13el8fCkOZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});